/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrintRouteImport } from './routes/print'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SlideWeekRouteImport } from './routes/slide/$week'
import { Route as SlidesIndexRouteImport } from './routes/slides/index'
import { Route as SlidesWeekRouteImport } from './routes/slides/$week'
import { Route as WeekWeekRouteImport } from './routes/week/$week'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRoute = PrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SlideWeekRoute = SlideWeekRouteImport.update({
  id: '/slide/$week',
  path: '/slide/$week',
  getParentRoute: () => rootRouteImport,
} as any)
const SlidesIndexRoute = SlidesIndexRouteImport.update({
  id: '/slides/',
  path: '/slides/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlidesWeekRoute = SlidesWeekRouteImport.update({
  id: '/slides/$week',
  path: '/slides/$week',
  getParentRoute: () => rootRouteImport,
} as any)
const WeekWeekRoute = WeekWeekRouteImport.update({
  id: '/week/$week',
  path: '/week/$week',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/print': typeof PrintRoute
  '/resources': typeof ResourcesRoute
  '/slide/$week': typeof SlideWeekRoute
  '/slides/$week': typeof SlidesWeekRoute
  '/week/$week': typeof WeekWeekRoute
  '/slides/': typeof SlidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/print': typeof PrintRoute
  '/resources': typeof ResourcesRoute
  '/slide/$week': typeof SlideWeekRoute
  '/slides/$week': typeof SlidesWeekRoute
  '/week/$week': typeof WeekWeekRoute
  '/slides': typeof SlidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/print': typeof PrintRoute
  '/resources': typeof ResourcesRoute
  '/slide/$week': typeof SlideWeekRoute
  '/slides/$week': typeof SlidesWeekRoute
  '/week/$week': typeof WeekWeekRoute
  '/slides/': typeof SlidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/print'
    | '/resources'
    | '/slide/$week'
    | '/slides/$week'
    | '/week/$week'
    | '/slides/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/print'
    | '/resources'
    | '/slide/$week'
    | '/slides/$week'
    | '/week/$week'
    | '/slides'
  id:
    | '__root__'
    | '/'
    | '/print'
    | '/resources'
    | '/slide/$week'
    | '/slides/$week'
    | '/week/$week'
    | '/slides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrintRoute: typeof PrintRoute
  ResourcesRoute: typeof ResourcesRoute
  SlideWeekRoute: typeof SlideWeekRoute
  SlidesWeekRoute: typeof SlidesWeekRoute
  WeekWeekRoute: typeof WeekWeekRoute
  SlidesIndexRoute: typeof SlidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print': {
      id: '/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof PrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slide/$week': {
      id: '/slide/$week'
      path: '/slide/$week'
      fullPath: '/slide/$week'
      preLoaderRoute: typeof SlideWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slides/': {
      id: '/slides/'
      path: '/slides'
      fullPath: '/slides/'
      preLoaderRoute: typeof SlidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slides/$week': {
      id: '/slides/$week'
      path: '/slides/$week'
      fullPath: '/slides/$week'
      preLoaderRoute: typeof SlidesWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/week/$week': {
      id: '/week/$week'
      path: '/week/$week'
      fullPath: '/week/$week'
      preLoaderRoute: typeof WeekWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrintRoute: PrintRoute,
  ResourcesRoute: ResourcesRoute,
  SlideWeekRoute: SlideWeekRoute,
  SlidesWeekRoute: SlidesWeekRoute,
  WeekWeekRoute: WeekWeekRoute,
  SlidesIndexRoute: SlidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
